### ISSUE TITLE
[BUG] Invalid Logo URL for Orgs

### ISSUE THREAD

**Issue by henry232323** [Dymerz/RSI-Scraper#4]
**Describe the bug**
External URLs get prefixed with the wrong domain. Right now I have only tested this for orgs and their logos, but I expect that any external url for various page resources that are generated from links are probably getting this as a result of prefixing a URL with the RSI domain, even if some links aren't relative but are instead absolute.

**To Reproduce**
Look up an org that still has one of the default logos
https://api.starcitizen-api.com/API_KEY/v1/live/organization/FSII

The logo ends up being
`https://robertsspaceindustries.comhttps://cdn.robertsspaceindustries.com/static/images/organization/defaults/logo/corp.jpg`
instead of just
`https://cdn.robertsspaceindustries.com/static/images/organization/defaults/logo/corp.jpg`

**Comment by Dymerz** [comment]
Hello and thank you for the report !

Indeed, it appears that RSI loves switches between relative and absolute URL, instead of simply remove the string concatenation ([here](https://github.com/Dymerz/RSI-Scraper/blob/bec6fe2af89ab2316fcf76223dc2b3639937f6a8/rsi_scraper/organization.py#L107)) it would be beneficial to create a function that takes the URL and determines whether it is a relative or absolute URL. If it is relative, the function should add the RSI prefix, otherwise, it should leave the URL as is. This would streamline the handling of links and ensure consistency throughout the code.

I can make these changes over the weekend. Alternatively, if you feel comfortable doing so, you can create a PR . 🙂

**Comment by henry232323** [comment]
I'll go ahead and PR that

**Comment by Dymerz** [comment]
Thanks for your contribution !
Fix released in [0.6.8](https://github.com/Dymerz/RSI-Scraper/releases/tag/0.6.8)
